{{ if .Values.global.cocoUpstream }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-sandboxed-containers-operator
  namespace: openshift-sandboxed-containers-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: sandboxed-containers-operator
  source: osc-upstream-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: sandboxed-containers-operator.v1.7.0
{{ end }}