{{ }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kbs-operator-system
  namespace: kbs-operator-system
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: trustee-operator
  source: kbs-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: trustee-operator.v0.0.1
