global:
  cocoUpstream: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

kbs:
  # Do you do internal HTTPS for the KBS
  https:
    enabled: false
  certAuth:
    enabled: false
  publicKey: secret/data/hub/kbsPublicKey
  privateKey: secret/data/global/kbsPrivateKey
  kbsres1: secret/data/hub/kbsres1
